import API from '../../api';

export const getUsers = () => API.get('/admin/users');
export const getAds = () => API.get('/admin/ads');
export const getDeposits = () => API.get('/admin/deposits');
export const getWithdrawals = () => API.get('/admin/withdrawals');
export const getTickets = () => API.get('/admin/tickets');
export const getPlans = () => API.get('/admin/plans');
export const getReferrals = () => API.get('/admin/referrals');
export const getRefSettings = () => API.get('/admin/referral-settings');
export const getSettings = () => API.get('/admin/settings');
export const getStats = () => API.get('/admin/stats');
export const getAdViewLog = () => API.get('/admin/ad-view-log');
export const getAdRequests = () => API.get('/admin/ad-requests');
export const getKycRequests = () => API.get('/admin/kyc');
export const getPlanPurchases = () => API.get('/admin/plan-purchases');
export const getEasypaisa = () => API.get('/admin/easypaisa');
export const getEmails = () => API.get('/admin/emails');
export const getWithdrawSettings = () => API.get('/admin/withdraw-settings');
export const getAdvertiserManagement = () => API.get('/admin/advertiser-management');
export const getAdvertiserDetail = (userId) => API.get(`/admin/advertiser-management/${userId}`);
export const createAd = (data) => API.post('/admin/ads', data);
export const toggleAd = (id) => API.put(`/admin/ads/${id}/toggle`);
export const deleteAd = (id) => API.delete(`/admin/ads/${id}`);
export const toggleUser = (id) => API.put(`/admin/users/${id}/toggle`);
export const updateUserBalance = (id, balance) => API.put(`/admin/users/${id}/balance`, { balance });
export const confirmDeposit = (id) => API.put(`/admin/deposits/${id}/confirm`);
export const rejectDeposit = (id) => API.put(`/admin/deposits/${id}/reject`);
export const approveWithdrawal = (id) => API.put(`/admin/withdrawals/${id}/approve`);
export const rejectWithdrawal = (id) => API.put(`/admin/withdrawals/${id}/reject`);
export const markSentWithdrawal = (id, formData) => API.post(`/admin/withdrawals/${id}/mark-sent`, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
export const replyTicket = (id, message) => API.post(`/admin/tickets/${id}/reply`, { message });
export const closeTicket = (id) => API.put(`/admin/tickets/${id}/close`);
export const addPlan = (data) => API.post('/admin/plans', data);
export const updatePlan = (id, data) => API.put(`/admin/plans/${id}`, data);
export const deletePlan = (id) => API.delete(`/admin/plans/${id}`);
export const searchReferrals = (query) => API.get(`/admin/referrals?search=${query}`);
export const toggleRefBonus = (type, val) => API.put(`/admin/referral-settings/${type}`, { is_active: val });
export const addRefLevel = (type) => API.post(`/admin/referral-settings/${type}/levels`, {});
export const updateRefLevel = (id, data) => API.put(`/admin/referral-levels/${id}`, data);
export const deleteRefLevel = (id) => API.delete(`/admin/referral-levels/${id}`);
export const searchAdViewLog = (query) => API.get(`/admin/ad-view-log?search=${query}`);
export const addEmail = (email) => API.post('/admin/emails', { email });
export const updateEmail = (id, email) => API.put(`/admin/emails/${id}`, { email });
export const deleteEmail = (id) => API.delete(`/admin/emails/${id}`);
export const toggleEasypaisa = (id) => API.put(`/admin/easypaisa/${id}/toggle`);
export const deleteEasypaisa = (id) => API.delete(`/admin/easypaisa/${id}`);
export const addEasypaisa = (data) => API.post('/admin/easypaisa', data);

export const updateWithdrawToggle = (enabled) => API.put('/admin/withdraw-settings/toggle', { enabled });
export const updateWithdrawDuration = (hours) => API.put('/admin/withdraw-settings/duration', { hours });
export const updateWithdrawSchedule = (timePkt) => API.put('/admin/withdraw-settings/schedule', { time_pkt: timePkt });
export const updateAdBudgetRate = (rate, welcomeMsg) => API.put('/admin/ad-budget-rate', { rate_pkr: rate, welcome_message: welcomeMsg });
export const updateMinCampaignUsers = (value) => API.put('/admin/settings/min_campaign_users', { value: String(value) });
export const updateFreePlanDays = (days) => API.put('/admin/free-plan-days', { days });
export const approveAdRequest = (id) => API.put(`/admin/user-ad-requests/${id}/approve`, { admin_note: '' });
export const rejectAdRequest = (id) => API.put(`/admin/user-ad-requests/${id}/reject`, { admin_note: '' });
export const approveKyc = (id) => API.put(`/admin/kyc/${id}/approve`, { admin_note: '' });
export const rejectKyc = (id, note) => API.put(`/admin/kyc/${id}/reject`, { admin_note: note || '' });
export const markKycAsSeen = () => API.post('/admin/kyc/mark-seen');
export const approvePlanPurchase = (id) => API.put(`/admin/plan-purchases/${id}/approve`, { admin_note: '' });
export const rejectPlanPurchase = (id) => API.put(`/admin/plan-purchases/${id}/reject`, { admin_note: '' });

export const updateSetting = (key, value) => API.put(`/admin/settings/${key}`, { value });
